// Reads the client's db.json and generates seed.sql for MySQL.
// Run:  node generate_seed.js   (writes seed.sql next to this file)
//
// Notes:
//  * All fields are migrated FAITHFULLY from db.json (same data).
//  * The password is ALSO copied into the separate `passwords`
//    table (the course's "users + passwords" requirement). The
//    original users fields – including website – are left as-is.
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const db = JSON.parse(readFileSync(join(here, '../../my-app/db.json'), 'utf8'));

// SQL-escape a value: NULL, number, or quoted string.
const q = (v) => {
  if (v === null || v === undefined || v === '') return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
};

const rows = (list, cols, map) =>
  list.map((it) => `  (${map(it).map(q).join(', ')})`).join(',\n');

const out = [];
out.push('-- Auto-generated by generate_seed.js – do not edit by hand.');
out.push('USE fullstack6;\n');

// role: yael is the system admin; everyone else is a regular user.
out.push('INSERT INTO users (id, username, name, email, phone, website, role) VALUES');
out.push(rows(db.users, 7, (u) =>
  [u.id, u.username, u.name, u.email, u.phone, u.website, u.username === 'yael' ? 'admin' : 'user']) + ';\n');

out.push('INSERT INTO passwords (user_id, password) VALUES');
out.push(rows(db.users, 2, (u) => [u.id, u.password]) + ';\n');

out.push('INSERT INTO todos (id, user_id, title, completed) VALUES');
out.push(rows(db.todos, 4, (t) => [t.id, t.userId, t.title, t.completed]) + ';\n');

out.push('INSERT INTO posts (id, user_id, title, body) VALUES');
out.push(rows(db.posts, 4, (p) => [p.id, p.userId, p.title, p.body]) + ';\n');

out.push('INSERT INTO comments (id, post_id, user_id, name, email, body) VALUES');
out.push(rows(db.comments, 6, (c) => [c.id, c.postId, c.userId, c.name, c.email, c.body]) + ';\n');

writeFileSync(join(here, 'seed.sql'), out.join('\n'));
console.log('Wrote seed.sql:',
  `${db.users.length} users, ${db.todos.length} todos, ${db.posts.length} posts,`,
  `${db.comments.length} comments`);
